- name: Terminate all EC2 instances and its resources (VPC, Security Groups, etc)
  hosts: localhost
  connection: local
  vars:
    region: eu-central-1
    the_tags:
      env: demo
  gather_facts: false
  tasks:
    - name: Fetch info about the EC2 instances # We need the VPC ID to delete the VPC
      amazon.aws.ec2_instance_info:
        filters:
          "tag:env": demo
          instance-state-name: ["running"]
        region: "{{ region }}"
      register: ec2_instances

    - name: Terminate every running instance in a region with tag {{ the_tags }}
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: terminated
        filters:
          tag:env: "{{ the_tags.env }}"
      register: ec2_instance

    - name: Delete Key Pair
      amazon.aws.ec2_key:
        name: "{{ ec2_instances.instances[0].key_name }}"
        region: "{{ region }}"
        state: absent
      when: ec2_instances.instances[0].key_name is defined

    - name: Delete Security Group
      amazon.aws.ec2_security_group:
        name: "Postgres Demo SG"
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined

    - name: Delete Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
        subnets:
          - "{{ ec2_instances.instances[0].network_interfaces[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
          - dest: ::/0
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined

    - name: Delete etcd cluster Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
        cidr: 10.0.1.0/24
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined
    
    - name: Delete Network Load Balancer
      community.aws.elb_network_lb:
        name: patroni-nlb
        state: absent

    - name: Delete target group
      community.aws.elb_target_group:
        name: patroni-tg
        region: "{{ region }}"
        state: absent

    - name: Delete patroni cluster Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
        cidr: 10.0.2.0/24
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined
    
    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
        tags:
          env: demo
      when: ec2_instances.instances[0].network_interfaces[0].vpc_id is defined

    - name: Delete S3 bucket and its objects
      amazon.aws.s3_bucket:
        name: patroni-demo-bucket
        region: "{{ region }}"
        force: true
        state: absent

    - name: Delete IAM Role
      community.aws.iam_role:
        name: PatroniWALRole
        region: "{{ region }}"
        state: absent
        tags:
          env: demo