- name: Terminate all EC2 instances and its resources (VPC, Security Groups, etc)
  hosts: localhost
  connection: local
  vars:
    the_tags:
      env: demo
  gather_facts: false
  tasks:
    - name: Fetch info about the EC2 instances # We need the VPC ID to delete the VPC
      amazon.aws.ec2_instance_info:
        filters:
          "tag:env": demo
          instance-state-name: ["running"]
        region: eu-central-1
      register: ec2_instances

    - name: Terminate every running instance in a region with tag {{ the_tags }}
      amazon.aws.ec2_instance:
        region: eu-central-1
        state: terminated
        filters:
          tag:env: "{{ the_tags.env }}"
      register: ec2_instance

    - name: Remove the insance ID from the group "{{ the_tags.env }}" in the inventory file
      ansible.builtin.lineinfile:
        path: "ansible/hosts"
        regexp: "^{{ item }}.*$"
        state: absent
      with_items: "{{ ec2_instance.terminate_success }}"

    - name: Delete Key Pair
      amazon.aws.ec2_key:
        name: "{{ ec2_instances.instances[0].key_name }}"
        region: eu-central-1
        state: absent

    - name: Delete Security Group
      amazon.aws.ec2_security_group:
        name: "Postgres Demo SG"
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: eu-central-1
        state: absent
        tags:
          env: demo

    - name: Delete Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: eu-central-1
        state: absent
        tags:
          env: demo
        subnets:
          - "{{ ec2_instances.instances[0].network_interfaces[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
          - dest: ::/0

    - name: Delete Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: eu-central-1
        state: absent
        tags:
          env: demo
        cidr: 10.0.0.0/16
    
    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: eu-central-1
        state: absent
        tags:
          env: demo

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ ec2_instances.instances[0].network_interfaces[0].vpc_id }}"
        region: eu-central-1
        state: absent
        tags:
          env: demo

    - name: Delete S3 Bucket
      amazon.aws.s3_bucket:
        name: patroni-demo-bucket
        region: eu-central-1
        state: absent
        tags:
          env: demo