- name: Create Fedora CoreOS and its needed resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_type: t2.micro
    instance_count: 3
    instance_region: eu-central-1
    ami_id: ami-01616b3a6ec881521 # Fedora CoreOS
    ec2_tags:
      cluster: etcd
      env: demo
  tasks:
    - name: Prepare all folders needed
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - tmp
        - keys
        - bin
        - certs

    - include_tasks: network_conf-task.yml

    - include_tasks: keys_and_certs-task.yml

    - name: Prepare ignition file # Converting Butane to Ignition
      ansible.builtin.shell: podman run --interactive --rm --security-opt label=disable --volume ${PWD}:/pwd --workdir /pwd quay.io/coreos/butane:release -d /pwd --pretty --strict butane.etcd.yaml > tmp/etcd.ign

    - name: Start Fedora CoreOS instances
      amazon.aws.ec2_instance:
        state: running
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        count: "{{ instance_count }}"
        region: "{{ instance_region }}"
        network:
          assign_public_ip: true
        security_group: "{{ sg.group_name }}"
        vpc_subnet_id: "{{ etcd_subnet.subnet.id }}"
        key_name: "{{ key_pair.key.name }}"
        tags: "{{ ec2_tags }}"
        user_data: "{{ lookup('file', 'tmp/etcd.ign')|string }}"
      register: ec2_instance

