
# Tasks for generating TLS certs, SSH keys and a discovery service endpoint the for etcd cluster

- name: Prepare TLS Certs for HTTPS etcd comms and keys for the etcd cluster
  ansible.builtin.shell: ./gen-root-ca.sh && ./gen-ec2-keys.sh

- name: create key pair using key_material obtained using 'file' lookup plugin
  amazon.aws.ec2_key:
    name: etcd
    key_material: "{{ lookup('file', 'keys/core.pub') }}"
    tags:
      env: demo
  register: key_pair

- name: Create a new etcd discovery service cluster
  ansible.builtin.shell: curl https://discovery.etcd.io/new?size={{ instance_count }} > tmp/etcd-discovery-cluster.txt