- name: Prepare SSL certificates
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create private key  # Root private key
      community.crypto.openssl_privatekey:
        path: /root/aws-postgresql-demo/certs/etcd.pem
        type: RSA
        size: 4096

    - name: Generate public key  # Root public key
      community.crypto.openssl_publickey:
        path: /root/aws-postgresql-demo/certs/etcd-client.pem
        privatekey_path: /root/aws-postgresql-demo/certs/etcd.pem

    - name: Generate Certificate Signing Request with a private key # Root CA certificate signing request
      community.crypto.openssl_csr:
        path: /root/aws-postgresql-demo/certs/etcd.csr
        privatekey_path: /root/aws-postgresql-demo/certs/etcd.pem
        common_name: etcd-root-ca
      register: csr

    - name: Generate a self-signed certificate # Root CA certificate
      community.crypto.x509_certificate:
        path: /root/aws-postgresql-demo/certs/etcd-root-ca.pem
        privatekey_path: /root/aws-postgresql-demo/certs/etcd.pem
        csr_path: /root/aws-postgresql-demo/certs/etcd.csr
        provider: selfsigned
