- name: Create a Fedora CoreOS instance
  hosts: localhost
  connection: local
  vars:
    inventory_file: /root/aws-postgresql-demo/ansible/hosts
    ec2_tags:
      cluster: etcd
  gather_facts: false
  tasks:
    - name: Terminate every running instance in a region with the tag {{ ec2_tags.cluster }}}
      amazon.aws.ec2_instance:
        region: eu-central-1
        state: terminated
        filters:
          tag:cluster: "{{ ec2_tags.cluster }}"
      register: ec2_instance

    - name: Remove the insance ID from the group "{{ ec2_tags.cluster }}" in the inventory file
      ansible.builtin.lineinfile:
        path: "{{ inventory_file }}"
        regexp: "^{{ item }}.*$"
        state: absent
      with_items: "{{ ec2_instance.terminate_success }}"