{
 "title": "Patroni Airlock Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "query_result(airlock_config_semaphore_slots)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$group</span></h1>"
   }
  },
  {
   "title": "Lock Holders",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airlock_database_semaphore_lock_holders{group=\"patroni-airlock\", exported_group=\"default\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pre-Reboot Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airlock_v1_pre_reboot_incoming_requests_total{group=\"patroni-airlock\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Steady State Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airlock_v1_steady_state_incoming_requests_total{group=~\"$group\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}