{
 "title": "PostgreSQL Patroni",
 "description": "Patroni dashboard.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "scope_name", "label": "Scope Name", "query": { "query": "query_result(patroni_version)" } },
   { "name": "instance", "label": "instance", "query": { "query": "query_result(patroni_version)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style='color:#5991A7;font-weight:bold;text-align:center;font-style:italic'>Data for <span style='color:#e68a00'>$instance</span> with <span style='color:#e68a00'>$interval</span> resolution</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Patroni Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_version{instance=~\"$instance\", scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{instance=~\"$instance\", scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "Patroni Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_primary{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Replica",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_replica{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Standby Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_standby_leader{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni Autofailover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_is_paused{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_server_version{instance=~\"$instance\", scope=~\"$scope_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postmaster_start_time{instance=~\"$instance\", scope=~\"$scope_name\"}*1000"
    }
   ]
  },
  {
   "title": "PostgreSQL Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_running{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Running (Timeline)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_timeline{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Pending Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_pending_restart{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Replay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_xlog_paused{instance=~\"$instance\", scope=~\"$scope_name\"}"
    }
   ]
  },
  {
   "title": "Patroni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Patroni Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_primary{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Patroni Secondary Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "patroni_replica{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL Replay Paused",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_paused{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Primary WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_location{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas Received WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_received_location{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas Replayed WAL Location",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "patroni_xlog_replayed_location{scope=~\"$scope_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}