- name: Create Fedora CoreOS and its needed resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_type: t2.micro
    instance_count: 1
    instance_region: eu-central-1
    ami_id: ami-04d3750b706767b83 # Fedora CoreOS
    ec2_tags:
      cluster: monitoring
      env: demo
    patroni_tags:
      cluster: patroni
      env: demo
    grafana_password: "grafana"
  tasks:
    - name: Prepare all folders needed
      ansible.builtin.file:
        path: "../{{ item }}"
        state: directory
      with_items:
        - tmp
        - keys
        - bin
        - certs

    - include_tasks: ../network_conf-task.yml

    - include_tasks: ../keys_and_certs-task.yml

    - name: Get Private DNS of the patroni and etcd Cluster
      set_fact:
        patroni_private_ips: "{{ groups['tag_cluster_patroni'] }}"
        etcd_private_ips: "{{ groups['tag_cluster_etcd'] }}"

    - name: Create IP Addresses File
      ansible.builtin.template:
        src: prometheus-template.j2
        dest: ../tmp/prometheus.yml

    - name: Prepare remote ignition file # Converting Butane to Remote Ignition
      ansible.builtin.shell: podman run --interactive --rm --security-opt label=disable --volume ${PWD}/../:/pwd --workdir /pwd quay.io/coreos/butane:release -d /pwd --pretty --strict cluster-monitoring/butane.monitoring.remote.yaml > ../tmp/monitoring.remote.ign

    - name: Uploading the ignition file to S3
      ansible.builtin.shell: aws s3 cp ../tmp/monitoring.remote.ign s3://private-ign-files/monitoring.remote.ign

    - name: Prepare ignition file # Converting Butane to Ignition
      ansible.builtin.shell: podman run --interactive --rm --security-opt label=disable --volume ${PWD}/../:/pwd --workdir /pwd quay.io/coreos/butane:release -d /pwd --pretty --strict cluster-monitoring/butane.monitoring.yaml > ../tmp/monitoring.ign

    - name: Create IAM Role for monitoring Role
      community.aws.iam_role:
        name: monitoringRole
        state: present
        region: "{{ instance_region }}"
        assume_role_policy_document: "{{ lookup('file', './assume_role_policy.json')|string }}"
        tags:
          Name: monitoringRole
          env: demo
      register: iam_role

    - name: Create instance profile for monitoring Role
      amazon.aws.iam_instance_profile:
        name: monitoringInstanceProfile
        state: present
        region: "{{ instance_region }}"
        role: "{{ iam_role.role_name }}"
        tags:
          Name: monitoringInstanceProfile
          env: demo
      register: iam_instance_profile
    
    - name: Attach S3 Policy to monitoring Role
      amazon.aws.iam_policy:
        policy_name: monitoringRolePolicy
        iam_type: role
        iam_name: "{{ iam_role.role_name }}"
        state: present
        region: "{{ instance_region }}"
        policy_json : "{{ lookup('file', './monitoring-role-policy.json')|string }}"

    - name: Start Fedora CoreOS instances
      amazon.aws.ec2_instance:
        state: running
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        count: "{{ instance_count }}"
        region: "{{ instance_region }}"
        network:
          assign_public_ip: true
        security_group: "{{ sg.group_name }}"
        vpc_subnet_id: "{{ monitoring_subnet.subnet.id }}"
        key_name: "{{ key_pair.key.name }}"
        tags: "{{ ec2_tags }}"
        user_data: "{{ lookup('file', '../tmp/monitoring.ign')|string }}"
        iam_instance_profile: "{{ iam_instance_profile.iam_instance_profile.instance_profile_name }}"
      register: ec2_instance

    - name: Create public ip list
      set_fact:
        monitoring_public_ip: "{{ ec2_instance.instances | map(attribute='public_ip_address') | list }}"

    - name: Pause for 30 seconds to let Grafana boot
      ansible.builtin.pause:
        seconds: 30

    - name: Check whether Grafana is alive
      uri:
        url: "http://{{ item }}:3000/api/health"
      register: grafana_response
      with_items: "{{ monitoring_public_ip }}"
      retries: 60
      delay: 5
      until: grafana_response.status == 200
      ignore_errors: yes

    - name: create prometheus datasource
      community.grafana.grafana_datasource:
        grafana_url: http://{{ item }}:3000/
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        name: Prometheus
        ds_type: prometheus
        ds_url: http://localhost:9090
        is_default: true
      with_items: "{{ monitoring_public_ip }}"

    - name: Import etcd Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ item }}:3000/"
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: "../grafana-dashboards/etcd.json"
      with_items: "{{ monitoring_public_ip }}"

    - name: Import Patroni Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ item }}:3000/"
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: "../grafana-dashboards/patroni.json"
      with_items: "{{ monitoring_public_ip }}"

    - name: Import Pgbouncer Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ item }}:3000/"
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: "../grafana-dashboards/pgbouncer.json"
      with_items: "{{ monitoring_public_ip }}"

    - name: Import Postgres Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ item }}:3000/"
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: "../grafana-dashboards/postgres.json"
      with_items: "{{ monitoring_public_ip }}"

    - name: Import Airlock Grafana dashboards
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ item }}:3000/"
        grafana_user: "admin"
        grafana_password: "{{ grafana_password }}"
        state: present
        commit_message: Updated by ansible
        overwrite: yes
        path: "../grafana-dashboards/airlock.json"
      with_items: "{{ monitoring_public_ip }}"