global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ha-postgres-monitor'

scrape_configs:
- job_name: 'postgres-exporter'
  static_configs:
  - targets: ['10.0.2.241:9187','10.0.2.245:9187','10.0.2.228:9187']
    labels:
      group: 'postgres'
- job_name: 'patroni'
  static_configs:
  - targets: ['10.0.2.241:8008','10.0.2.245:8008','10.0.2.228:8008']
    labels:
      group: 'patroni'
