- name: Terminating all EC2 instances running etcd
  hosts: localhost
  connection: local
  vars:
    ec2_tags:
      cluster: monitoring
  gather_facts: false
  tasks:
    - name: Terminate every running instance in a region with the tag {{ ec2_tags.cluster }}
      amazon.aws.ec2_instance:
        region: eu-central-1
        state: terminated
        filters:
          tag:cluster: "{{ ec2_tags.cluster }}"
      register: ec2_instance
